name: Build

on:
    push:
        paths-ignore:
            - "*.md"
    release:
        types: [created]

    workflow_dispatch: ~

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "PHP ${{ matrix.php }}"

        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1"]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2.3.3

            - name: Install PHP
              uses: shivammathur/setup-php@2.18.0
              with:
                  coverage: "none"
                  php-version: ${{ matrix.php }}

            - name: Validate composer.json
              run: composer validate --strict --no-check-lock --ansi

            - name: Install PHP dependencies
              run: composer install --no-interaction

            - name: Run PHPStan
              run: vendor/bin/phpstan

            - name: Run Psalm
              run: vendor/bin/psalm

            - name: Run PHPUnit
              run: vendor/bin/phpunit --colors=always
